spring:

  # Swagger UI 설정 추가
  springdoc:
    api-docs:
      enabled: true
      path: /api-docs
    swagger-ui:
      path: /swagger-ui.html
      enabled: true
      operations-sorter: alpha
      tags-sorter: alpha


  application:
    name: backend
    
  output:
    ansi:
      enabled: always

  security:
    basic:
      enabled: false

  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_schema: public  # 스키마 설정 추가
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/lms?characterEncoding=UTF-8
    username: postgres
    password: popost

  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

server:
  port: 8081
#  servlet:
#    context-path: /api

my_value:
  key: "1111"

#LOGGING_LEVEL:
#  org:
#    springframework:
#      security: DEBUG

