spring:

  application:
    name: backend
    
  output:
    ansi:
      enabled: always

  security:
    basic:
      enabled: false

  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_schema: public  # 스키마 설정 추가
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/lms?characterEncoding=UTF-8
    username: postgres
    password: popost

  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# Swagger UI 설정 추가
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

server:
  port: 8081
#  servlet:
#    context-path: /api

my_value:
  key: "1111"

# Redis 설정 추가
  redis:
    host: localhost
    port: 6379


#LOGGING_LEVEL:
#  org:
#    springframework:
#      security: DEBUG


