spring:
  application:
    name: backend
    
  output:
    ansi:
      enabled: always

  security:
    basic:
      enabled: false

  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_schema: public
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/lms?characterEncoding=UTF-8
    username: postgres
    password: popost

  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

server:
  port: 8081